#for DE in CMPLNT_NUM CMPLNT_TO_DT CMPLNT_NUM CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM RPT_DT KY_CD OFNS_DESC 
#for DE in PD_CD PD_DESC CRM_ATPT_CPTD_CD LAW_CAT_CD JURIS_DESC BORO_NM ADDR_PCT_CD 
for DE in CMPLNT_NUM CMPLNT_TO_DT CMPLNT_NUM CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM RPT_DT KY_CD OFNS_DESC PD_CD PD_DESC CRM_ATPT_CPTD_CD LAW_CAT_CD JURIS_DESC BORO_NM ADDR_PCT_CD LOC_OF_OCCUR_DESC PREM_TYP_DESC PARKS_NM HADEVELOPT X_COORD_CD Y_COORD_CD Latitude Longitude Lat_Lon
do
    /usr/bin/hadoop fs -rm -r summary_$DE.out type_$DE.out
    spark-submit $DE.py /user/tr1312/crime_data.csv
    /usr/bin/hadoop fs -getmerge summary_$DE.out summary_$DE.out
done

